name: Automated Testing Demo

on:
  pull_request:
    branches:
      - main
      - feedback
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          #flutter-version: '3.22.2'
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Run automated tests
        run: |
          dart format --output=none ./lib
          flutter analyze --no-fatal-infos --no-fatal-warnings ./lib
          flutter test automated_tests_do_not_touch
